HDBMMVC/Controllers/ActivitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HDBMMVC.Models;
using Microsoft.AspNet.Identity;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using OfficeOpenXml;
using QXHMVC.Models;

namespace HDBMMVC.Controllers
{
    public class ActivitiesController : Controller
    {
        private DbModel db = new DbModel();

        // GET: Activities
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public ActionResult MyIndex()
        {
            string userid = User.Identity.GetUserId().ToString();
            return View(db.Activities.Where(r => r.UserId == userid).ToList());
        }
        [Authorize(Roles ="Admin")]
        public ActionResult Admin()
        {
            return View(db.Activities.ToList());
        }

        // GET: Activities/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            if (activity.UserId != User.Identity.GetUserId().ToString() && !User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // GET: Activities/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Activities/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Major,Sno,Phone,Email")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                activity.UserId = User.Identity.GetUserId().ToString();
                activity.CreateId= Guid.NewGuid().ToString();
                db.Activities.Add(activity);
                db.SaveChanges();
                return RedirectToAction("CreateSuccess", new { CreateId = activity.CreateId });
            }

            return View(activity);
        }
        [Authorize]
        public ActionResult CreateSuccess(string CreateId)
        {
            ViewBag.createid = CreateId;
            return View();
        }

        // GET: Activities/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            if (activity.UserId != User.Identity.GetUserId().ToString() && !User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // POST: Activities/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Major,Sno,Phone,Email")] Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(activity);
        }

        // GET: Activities/Delete/5
        [Authorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            if (activity.UserId != User.Identity.GetUserId().ToString() && !User.IsInRole("Admin"))
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        // POST: Activities/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Activity activity = db.Activities.Find(id);
            db.Activities.Remove(activity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        /// <summary>
        /// 表头的样式
        /// </summary>
        /// <param name="workbook"></param>
        /// <param name="sheet"></param>
        [Authorize]
        public void CreateHeadStyle(HSSFWorkbook workbook, HSSFSheet sheet)
        {
            //创建行
            HSSFRow row = sheet.CreateRow(0) as HSSFRow;
            //创建列
            var cell0 = row.CreateCell(0);
            var cell1 = row.CreateCell(1);
            var cell2 = row.CreateCell(2);
            var cell3 = row.CreateCell(3);
            var cell4 = row.CreateCell(4);
            var cell5 = row.CreateCell(5);
            var cell6 = row.CreateCell(6);
            cell0.SetCellValue("序号");
            cell1.SetCellValue("姓名");
            cell2.SetCellValue("专业");
            cell3.SetCellValue("学号");
            cell4.SetCellValue("手机");
            cell5.SetCellValue("邮箱");
            cell6.SetCellValue("报名识别码");
            //创建列的样式
            HSSFCellStyle cstyle = workbook.CreateCellStyle() as HSSFCellStyle;
            //设置垂直居中
            cstyle.VerticalAlignment = VerticalAlignment.Center;
            //设置水平居中
            cstyle.Alignment = HorizontalAlignment.Center;

            cell0.CellStyle = cstyle;
            cell1.CellStyle = cstyle;
            cell2.CellStyle = cstyle;
            cell3.CellStyle = cstyle;
            cell4.CellStyle = cstyle;
            cell5.CellStyle = cstyle;
            cell6.CellStyle = cstyle;
        }

        /// <summary>
        /// 导出excel表
        /// </summary>
        [Authorize]
        public void ToExcel()
        {
            //创建一个Excel表
            HSSFWorkbook workbook = new HSSFWorkbook();

            HSSFSheet sheet = workbook.CreateSheet() as HSSFSheet;

            CreateHeadStyle(workbook, sheet);

            Response.AddHeader("Content-Disposition", "attachment;filename=活动报名表.xls");//导出后的文件名

            //查询数据库

            List<Activity> elist = db.Activities.ToList();
            //遍历集合
            for (int i = 0; i < elist.Count; i++)//遍历表数据
            {
                //创建行
                HSSFRow row = sheet.CreateRow(i + 1) as HSSFRow;
                //创建列
                row.CreateCell(0).SetCellValue(Convert.ToString(elist[i].Id));
                row.CreateCell(1).SetCellValue(Convert.ToString(elist[i].Name));
                row.CreateCell(2).SetCellValue(Convert.ToString(elist[i].Major));
                row.CreateCell(3).SetCellValue(Convert.ToString(elist[i].Sno));
                row.CreateCell(4).SetCellValue(Convert.ToString(elist[i].Phone));
                row.CreateCell(5).SetCellValue(Convert.ToString(elist[i].Email));
                row.CreateCell(6).SetCellValue(Convert.ToString(elist[i].CreateId));
            }

            //内存流
            MemoryStream ms = new MemoryStream();

            workbook.Write(ms);

            Response.BinaryWrite(ms.ToArray());
        } 
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HDBMMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 社团活动报名系统</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .navbar {
            background-color: rgba(255, 255, 255, .05);
            box-shadow: 0 4px 8px rgba(0,0,0,.05);
            border: none;
        }

            .navbar a {
                color: black !important;
            }

                .navbar a:hover {
                    color: #f29901 !important;
                }

        img {
            transition: all 0.6s;
        }

            img:hover {
                transform: scale(1.2);
            }
    </style>

</head>
<body>
    <div class="navbar navbar-fixed-top navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("社团活动报名系统", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首页", "Index", "Home")</li>
                    <li>@Html.ActionLink("活动", "Index", "Activities")</li>
                    <li>@Html.ActionLink("关于", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <footer>
            <p>&copy; @DateTime.Now.Year 社团活动报名系统</p>
            <p>浙ICP备2022000135号 浙公网安备33078102100239号</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>